version: "3.9"
services:
    edagames-web:
        build: .
        ports:
            - "8000:8000"
        volumes: 
            - .:/edagames-django
        environment: 
            - SECRET_KEY=${SECRET_KEY}
            - SECRET_KEY_JWT=${SECRET_KEY_JWT}
            - SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY=${SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY}
            - SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET=${SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET}
            - SERVER_URL=https://0.0.0.0
            - SERVER_PORT=5000
