version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Create test reports directory
          command: mkdir /tmp/test-artifacts
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install dependencies-dev
          command: pip install -r dev-requirements.txt
      - run:
          name: Run Flake8 checks
          command: flake8
      - run:
          name: Setup Code Climate test-reporter
          command: |
              # download test reporter as a static binary
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
              ./cc-test-reporter before-build
      - run:
          name: Running Tests
          command: coverage run manage.py test && coverage xml && coverage report -m
      - run:
          name: Update CodeClimate coverage report
          command: |
              ./cc-test-reporter after-build --exit-code $?

workflows:
  main:
    jobs:
      - build-and-test
