version: 2.1

jobs:
  build-and-test-js:
    docker:
      - image: cimg/node:14.18.1
    steps:
      - checkout:
          path: ~/javascript_test
      - run:
          name: update npm
          command: "sudo npm install --unsafe-perm -g npm@latest"
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: run space test
          command: npm test
  build-and-test:
    docker:
      - image: cimg/python:3.8.9
    steps:
      - checkout
      - run:
          name: Create test reports directory
          command: mkdir /tmp/test-artifacts
      - run:
          name: Install dependencies
          command: pipenv sync --dev
      - run:
          name: Run Flake8 checks
          command: pipenv run flake8
      - run:
          name: Setup Code Climate test-reporter
          command: |
              # download test reporter as a static binary
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
              ./cc-test-reporter before-build
      - run:
          name: Running Tests
          command: pipenv run coverage run manage.py test && pipenv run coverage xml && pipenv run coverage report -m
      - run:
          name: Update CodeClimate coverage report
          command: |
              ./cc-test-reporter after-build --exit-code $?
  build-and-upload-image:
    docker:
      - image: docker:20.10.14-git
    parameters:
      app_name:
        type: string
        description: Name of the application to build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py3-pip
            pip install awscli
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/<< parameters.app_name >>.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/<< parameters.app_name >>.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=<< parameters.app_name >> -t << parameters.app_name >> .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/<< parameters.app_name >>.tar << parameters.app_name >>
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/<< parameters.app_name >>.tar
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              aws ecr-public get-login-password --region us-east-1 \
                | docker login --username AWS --password-stdin ${ECR_REGISTRY}
              docker tag << parameters.app_name >> "${ECR_REGISTRY}/<< parameters.app_name >>:${CIRCLE_SHA1}"
              docker push "${ECR_REGISTRY}/<< parameters.app_name >>:${CIRCLE_SHA1}"
              docker tag << parameters.app_name >> "${ECR_REGISTRY}/<< parameters.app_name >>:latest"
              docker push "${ECR_REGISTRY}/<< parameters.app_name >>:latest"
            fi
  trigger-main-repo-update:
    docker:
      - image: curlimages/curl
    steps:
      - run:
          name: Update main repo
          command: |
            curl \
            -X POST \
            -H "Authorization: token $MACHINEUSER_GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/evbeda/edagames/dispatches \
            -d '{"event_type":"update_django"}'
workflows:
  main:
    jobs:
      - build-and-test-js
      - build-and-test
      - build-and-upload-image:
          app_name: edagames-django
          requires:
            - build-and-test
          context:
            - 'edagames-aws'
            - 'edagames'
      - trigger-main-repo-update:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
          context:
            - 'edagames'
