# Generated by Django 2.2.20 on 2022-04-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournamentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('finish', 'Finish')], default='pending', max_length=8),
        ),
    ]
