# Generated by Django 2.2.20 on 2022-10-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='status',
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tournament_bots', models.IntegerField(default=0)),
                ('final_tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_tournament', to='tournaments.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='championship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Championship'),
        ),
    ]
