# Generated by Django 2.2.20 on 2022-10-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20221017_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='tournament_bots',
            field=models.IntegerField(default=0),
        ),
    ]
