# Generated by Django 2.2.20 on 2022-10-28 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0006_tournament_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='final_tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='championship_final', to='tournaments.Tournament'),
        ),
        migrations.CreateModel(
            name='FinalTournamentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_tournament_registration', to='tournaments.Championship')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_tournament_registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
