# Generated by Django 2.2.20 on 2021-05-12 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
