# Generated by Django 2.2.20 on 2024-05-11 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_auto_20220505_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('city_zone', models.CharField(max_length=100)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('linkedin_profile', models.CharField(max_length=100)),
                ('github_username', models.CharField(max_length=100)),
                ('education_background', models.CharField(max_length=100)),
                ('english_level', models.CharField(max_length=50)),
                ('intro', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
