# Generated by Django 2.2.20 on 2024-05-12 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_auto_20240511_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
    ]
