from django.urls import (
    path,
)
from .views import (
    ChampionshipCreateView,
    ChampionshipHistoryView,
    CreateTournamentView,
    create_registration,
    delete_tournament,
    FinalistUserView,
    PendingTournamentListView,
    RegistrationTournamentView,
    TournamentGeneratorView,
    TournamentResultsView,
    TournamentListView,
)


app_name = 'tournaments'
urlpatterns = [
    path(
        'create_tournament/',
        CreateTournamentView.as_view(),
        name='create_tournament',
    ),
    path(
        'tournaments/<int:pk>/delete',
        delete_tournament,
        name='delete_tournament',
    ),
    path(
        'create_championship/',
        ChampionshipCreateView.as_view(),
        name='create_championship',
    ),
    path(
        'tournament_generator/',
        TournamentGeneratorView.as_view(),
        name='tournament_generator',
    ),
    path(
        'tournaments_history/',
        TournamentListView.as_view(),
        name='tournaments_history',
    ),
    path(
        'tournaments_pending/',
        PendingTournamentListView.as_view(),
        name='tournaments_pending',
    ),
    path(
        'tournament_results/<int:pk>/',
        TournamentResultsView.as_view(),
        name='tournament_results',
    ),
    path(
        'tournament_registration/',
        RegistrationTournamentView.as_view(),
        name='tournament_registration',
    ),
    path(
        'championship_list',
        ChampionshipHistoryView.as_view(),
        name='championship_list',
    ),
    path(
        'finalist_users/<int:pk>',
        FinalistUserView.as_view(),
        name='finalist_users',
    ),
    path(
        'create_registration/<int:championship_id>',
        create_registration,
        name="create_registration"
    )
]
