# Generated by Django 2.2.20 on 2021-05-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0004_auto_20210422_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='board_id',
        ),
        migrations.AddField(
            model_name='match',
            name='game_id',
            field=models.CharField(default='no-board-id', max_length=50),
            preserve_default=False,
        ),
    ]
