# Generated by Django 2.2.20 on 2021-05-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0005_auto_20210505_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='bot_one',
            new_name='bot_1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='bot_two',
            new_name='bot_2',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score_p_one',
            new_name='score_p_1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score_p_two',
            new_name='score_p_2',
        ),
    ]
