# Generated by Django 2.2.20 on 2021-05-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0008_bot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
