# Generated by Django 2.2.20 on 2021-05-17 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0009_delete_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='bot_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_1', to='auth_app.Bot'),
        ),
        migrations.AlterField(
            model_name='match',
            name='bot_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_2', to='auth_app.Bot'),
        ),
    ]
