# Generated by Django 2.2.20 on 2021-05-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0010_auto_20210517_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='user_one',
            new_name='user_1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='user_two',
            new_name='user_2',
        ),
    ]
