# Generated by Django 2.2.20 on 2021-05-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        ('development', '0011_auto_20210518_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_id', to='tournaments.Tournament'),
        ),
    ]
