# Generated by Django 2.2.20 on 2021-06-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_auto_20210608_1352'),
        ('tournaments', '0001_initial'),
        ('development', '0012_match_tournament_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='bot_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='bot_2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score_p_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score_p_2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user_2',
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
        migrations.CreateModel(
            name='MatchMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.Bot')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='development.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_challenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='development_challenge_related', to='auth_app.Bot')),
                ('bots_challenged', models.ManyToManyField(to='auth_app.Bot')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='development_challenge_related', to='tournaments.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(through='development.MatchMembers', to='auth_app.Bot'),
        ),
    ]
