# Generated by Django 2.2.20 on 2021-06-08 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0013_auto_20210608_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='bot_challenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='development_challenge_related', to='auth_app.Bot'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='development_challenge_related', to='tournaments.Tournament'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
    ]
