# Generated by Django 2.2.20 on 2021-06-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0015_auto_20210608_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmembers',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
