# Generated by Django 2.2.20 on 2022-04-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0016_matchmembers_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmembers',
            name='winner',
        ),
        migrations.AddField(
            model_name='matchmembers',
            name='match_result',
            field=models.IntegerField(default=0),
        ),
    ]
